/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRewardsIndexRouteImport } from './routes/_authenticated/rewards/index'
import { Route as AuthenticatedReferIndexRouteImport } from './routes/_authenticated/refer/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedBusinessesIndexRouteImport } from './routes/_authenticated/businesses/index'
import { Route as AuthenticatedBookIndexRouteImport } from './routes/_authenticated/book/index'
import { Route as GuestAuthLoginIndexRouteImport } from './routes/_guest/auth/login/index'
import { Route as GuestAuthForgotPasswordIndexRouteImport } from './routes/_guest/auth/forgot-password/index'
import { Route as AuthenticatedProfileEditIndexRouteImport } from './routes/_authenticated/profile/edit/index'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRewardsIndexRoute =
  AuthenticatedRewardsIndexRouteImport.update({
    id: '/rewards/',
    path: '/rewards/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReferIndexRoute = AuthenticatedReferIndexRouteImport.update({
  id: '/refer/',
  path: '/refer/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessesIndexRoute =
  AuthenticatedBusinessesIndexRouteImport.update({
    id: '/businesses/',
    path: '/businesses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookIndexRoute = AuthenticatedBookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const GuestAuthLoginIndexRoute = GuestAuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestAuthForgotPasswordIndexRoute =
  GuestAuthForgotPasswordIndexRouteImport.update({
    id: '/auth/forgot-password/',
    path: '/auth/forgot-password/',
    getParentRoute: () => GuestRouteRoute,
  } as any)
const AuthenticatedProfileEditIndexRoute =
  AuthenticatedProfileEditIndexRouteImport.update({
    id: '/profile/edit/',
    path: '/profile/edit/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof AuthenticatedBookIndexRoute
  '/businesses': typeof AuthenticatedBusinessesIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/refer': typeof AuthenticatedReferIndexRoute
  '/rewards': typeof AuthenticatedRewardsIndexRoute
  '/profile/edit': typeof AuthenticatedProfileEditIndexRoute
  '/auth/forgot-password': typeof GuestAuthForgotPasswordIndexRoute
  '/auth/login': typeof GuestAuthLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof AuthenticatedBookIndexRoute
  '/businesses': typeof AuthenticatedBusinessesIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/refer': typeof AuthenticatedReferIndexRoute
  '/rewards': typeof AuthenticatedRewardsIndexRoute
  '/profile/edit': typeof AuthenticatedProfileEditIndexRoute
  '/auth/forgot-password': typeof GuestAuthForgotPasswordIndexRoute
  '/auth/login': typeof GuestAuthLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_authenticated/book/': typeof AuthenticatedBookIndexRoute
  '/_authenticated/businesses/': typeof AuthenticatedBusinessesIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/refer/': typeof AuthenticatedReferIndexRoute
  '/_authenticated/rewards/': typeof AuthenticatedRewardsIndexRoute
  '/_authenticated/profile/edit/': typeof AuthenticatedProfileEditIndexRoute
  '/_guest/auth/forgot-password/': typeof GuestAuthForgotPasswordIndexRoute
  '/_guest/auth/login/': typeof GuestAuthLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/businesses'
    | '/profile'
    | '/refer'
    | '/rewards'
    | '/profile/edit'
    | '/auth/forgot-password'
    | '/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/businesses'
    | '/profile'
    | '/refer'
    | '/rewards'
    | '/profile/edit'
    | '/auth/forgot-password'
    | '/auth/login'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_guest'
    | '/_authenticated/book/'
    | '/_authenticated/businesses/'
    | '/_authenticated/profile/'
    | '/_authenticated/refer/'
    | '/_authenticated/rewards/'
    | '/_authenticated/profile/edit/'
    | '/_guest/auth/forgot-password/'
    | '/_guest/auth/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rewards/': {
      id: '/_authenticated/rewards/'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/refer/': {
      id: '/_authenticated/refer/'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof AuthenticatedReferIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/businesses/': {
      id: '/_authenticated/businesses/'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof AuthenticatedBusinessesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/book/': {
      id: '/_authenticated/book/'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof AuthenticatedBookIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_guest/auth/login/': {
      id: '/_guest/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof GuestAuthLoginIndexRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/auth/forgot-password/': {
      id: '/_guest/auth/forgot-password/'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof GuestAuthForgotPasswordIndexRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_authenticated/profile/edit/': {
      id: '/_authenticated/profile/edit/'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedProfileEditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBookIndexRoute: typeof AuthenticatedBookIndexRoute
  AuthenticatedBusinessesIndexRoute: typeof AuthenticatedBusinessesIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedReferIndexRoute: typeof AuthenticatedReferIndexRoute
  AuthenticatedRewardsIndexRoute: typeof AuthenticatedRewardsIndexRoute
  AuthenticatedProfileEditIndexRoute: typeof AuthenticatedProfileEditIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBookIndexRoute: AuthenticatedBookIndexRoute,
  AuthenticatedBusinessesIndexRoute: AuthenticatedBusinessesIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedReferIndexRoute: AuthenticatedReferIndexRoute,
  AuthenticatedRewardsIndexRoute: AuthenticatedRewardsIndexRoute,
  AuthenticatedProfileEditIndexRoute: AuthenticatedProfileEditIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface GuestRouteRouteChildren {
  GuestAuthForgotPasswordIndexRoute: typeof GuestAuthForgotPasswordIndexRoute
  GuestAuthLoginIndexRoute: typeof GuestAuthLoginIndexRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestAuthForgotPasswordIndexRoute: GuestAuthForgotPasswordIndexRoute,
  GuestAuthLoginIndexRoute: GuestAuthLoginIndexRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
