create table "public"."submissions_audit" (
    "id" uuid not null default gen_random_uuid(),
    "received_at" timestamp with time zone not null default now(),
    "raw_payload" jsonb,
    "clean_snapshot" jsonb,
    "lead_email" text,
    "partner_id" bigint generated by default as identity not null,
    "utm" jsonb,
    "lp_slug" text,
    "landing_page_url" text,
    "referrer" text,
    "first_visit_at" timestamp with time zone,
    "session_id" uuid default gen_random_uuid(),
    "consent" boolean not null default true,
    "status" text,
    "odoo_lead_id" uuid default gen_random_uuid(),
    "visitor_tx_msg_id" text,
    "partner_tx_msg_id" text,
    "request_ip" inet
);


alter table "public"."submissions_audit" enable row level security;

CREATE UNIQUE INDEX submissions_audit_partner_id_key ON public.submissions_audit USING btree (partner_id);

CREATE UNIQUE INDEX submissions_audit_pkey ON public.submissions_audit USING btree (id);

alter table "public"."submissions_audit" add constraint "submissions_audit_pkey" PRIMARY KEY using index "submissions_audit_pkey";

alter table "public"."submissions_audit" add constraint "submissions_audit_partner_id_key" UNIQUE using index "submissions_audit_partner_id_key";

grant delete on table "public"."submissions_audit" to "anon";

grant insert on table "public"."submissions_audit" to "anon";

grant references on table "public"."submissions_audit" to "anon";

grant select on table "public"."submissions_audit" to "anon";

grant trigger on table "public"."submissions_audit" to "anon";

grant truncate on table "public"."submissions_audit" to "anon";

grant update on table "public"."submissions_audit" to "anon";

grant delete on table "public"."submissions_audit" to "authenticated";

grant insert on table "public"."submissions_audit" to "authenticated";

grant references on table "public"."submissions_audit" to "authenticated";

grant select on table "public"."submissions_audit" to "authenticated";

grant trigger on table "public"."submissions_audit" to "authenticated";

grant truncate on table "public"."submissions_audit" to "authenticated";

grant update on table "public"."submissions_audit" to "authenticated";

grant delete on table "public"."submissions_audit" to "service_role";

grant insert on table "public"."submissions_audit" to "service_role";

grant references on table "public"."submissions_audit" to "service_role";

grant select on table "public"."submissions_audit" to "service_role";

grant trigger on table "public"."submissions_audit" to "service_role";

grant truncate on table "public"."submissions_audit" to "service_role";

grant update on table "public"."submissions_audit" to "service_role";


