create table "public"."dead_letters" (
    "id" uuid not null default gen_random_uuid(),
    "received_at" timestamp with time zone not null default now(),
    "raw_payload" jsonb,
    "clean_snapshot" jsonb,
    "lead_email" text,
    "partner_id" bigint generated by default as identity not null,
    "utm" jsonb,
    "lp_slug" text,
    "landing_page_url" text,
    "referrer" text,
    "first_visit_at" timestamp with time zone,
    "session_id" uuid default gen_random_uuid(),
    "consent" boolean not null default true,
    "status" text,
    "odoo_lead_id" uuid default gen_random_uuid(),
    "visitor_tx_msg_id" text,
    "partner_tx_msg_id" text,
    "request_ip" inet
);


grant delete on table "public"."dead_letters" to "anon";

grant insert on table "public"."dead_letters" to "anon";

grant references on table "public"."dead_letters" to "anon";

grant select on table "public"."dead_letters" to "anon";

grant trigger on table "public"."dead_letters" to "anon";

grant truncate on table "public"."dead_letters" to "anon";

grant update on table "public"."dead_letters" to "anon";

grant delete on table "public"."dead_letters" to "authenticated";

grant insert on table "public"."dead_letters" to "authenticated";

grant references on table "public"."dead_letters" to "authenticated";

grant select on table "public"."dead_letters" to "authenticated";

grant trigger on table "public"."dead_letters" to "authenticated";

grant truncate on table "public"."dead_letters" to "authenticated";

grant update on table "public"."dead_letters" to "authenticated";

grant delete on table "public"."dead_letters" to "service_role";

grant insert on table "public"."dead_letters" to "service_role";

grant references on table "public"."dead_letters" to "service_role";

grant select on table "public"."dead_letters" to "service_role";

grant trigger on table "public"."dead_letters" to "service_role";

grant truncate on table "public"."dead_letters" to "service_role";

grant update on table "public"."dead_letters" to "service_role";


