create table "public"."amenities" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "amenity_url" text,
    "branch_id" uuid not null,
    "is_available" boolean not null default true
);


CREATE UNIQUE INDEX amenities_pkey ON public.amenities USING btree (id);

alter table "public"."amenities" add constraint "amenities_pkey" PRIMARY KEY using index "amenities_pkey";

alter table "public"."amenities" add constraint "amenities_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES branches(id) not valid;

alter table "public"."amenities" validate constraint "amenities_branch_id_fkey";

grant delete on table "public"."amenities" to "anon";

grant insert on table "public"."amenities" to "anon";

grant references on table "public"."amenities" to "anon";

grant select on table "public"."amenities" to "anon";

grant trigger on table "public"."amenities" to "anon";

grant truncate on table "public"."amenities" to "anon";

grant update on table "public"."amenities" to "anon";

grant delete on table "public"."amenities" to "authenticated";

grant insert on table "public"."amenities" to "authenticated";

grant references on table "public"."amenities" to "authenticated";

grant select on table "public"."amenities" to "authenticated";

grant trigger on table "public"."amenities" to "authenticated";

grant truncate on table "public"."amenities" to "authenticated";

grant update on table "public"."amenities" to "authenticated";

grant delete on table "public"."amenities" to "service_role";

grant insert on table "public"."amenities" to "service_role";

grant references on table "public"."amenities" to "service_role";

grant select on table "public"."amenities" to "service_role";

grant trigger on table "public"."amenities" to "service_role";

grant truncate on table "public"."amenities" to "service_role";

grant update on table "public"."amenities" to "service_role";


