-- migrate:up
create table public.dead_letters (
                                     id uuid not null default gen_random_uuid(),
                                     received_at timestamptz not null default now(),
                                     raw_payload jsonb,
                                     clean_snapshot jsonb,
                                     lead_email text,
                                     partner_id bigint generated by default as identity not null,
                                     utm jsonb,
                                     lp_slug text,
                                     landing_page_url text,
                                     referrer text,
                                     first_visit_at timestamptz,
                                     session_id uuid default gen_random_uuid(),
                                     consent boolean not null default true,
                                     status text,
                                     odoo_lead_id uuid default gen_random_uuid(),
                                     visitor_tx_msg_id text,
                                     partner_tx_msg_id text,
                                     request_ip inet
);

grant delete, insert, references, select, trigger, truncate, update
  on table public.dead_letters to anon;

grant delete, insert, references, select, trigger, truncate, update
  on table public.dead_letters to authenticated;

grant delete, insert, references, select, trigger, truncate, update
  on table public.dead_letters to service_role;
