-- migrate:up
create table public.submissions_audit (
                                          id uuid not null default gen_random_uuid(),
                                          received_at timestamptz not null default now(),
                                          raw_payload jsonb,
                                          clean_snapshot jsonb,
                                          lead_email text,
                                          partner_id bigint generated by default as identity not null,
                                          utm jsonb,
                                          lp_slug text,
                                          landing_page_url text,
                                          referrer text,
                                          first_visit_at timestamptz,
                                          session_id uuid default gen_random_uuid(),
                                          consent boolean not null default true,
                                          status text,
                                          odoo_lead_id uuid default gen_random_uuid(),
                                          visitor_tx_msg_id text,
                                          partner_tx_msg_id text,
                                          request_ip inet
);

alter table public.submissions_audit enable row level security;

create unique index submissions_audit_partner_id_key on public.submissions_audit (partner_id);
create unique index submissions_audit_pkey on public.submissions_audit (id);

alter table public.submissions_audit add constraint submissions_audit_pkey
    primary key using index submissions_audit_pkey;

alter table public.submissions_audit add constraint submissions_audit_partner_id_key
    unique using index submissions_audit_partner_id_key;

grant delete, insert, references, select, trigger, truncate, update
  on table public.submissions_audit to anon;

grant delete, insert, references, select, trigger, truncate, update
  on table public.submissions_audit to authenticated;

grant delete, insert, references, select, trigger, truncate, update
  on table public.submissions_audit to service_role;
