/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestAuthLoginIndexRouteImport } from './routes/_guest/auth/login/index'
import { Route as GuestAuthForgotPasswordIndexRouteImport } from './routes/_guest/auth/forgot-password/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestAuthLoginIndexRoute = GuestAuthLoginIndexRouteImport.update({
  id: '/_guest/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestAuthForgotPasswordIndexRoute =
  GuestAuthForgotPasswordIndexRouteImport.update({
    id: '/_guest/auth/forgot-password/',
    path: '/auth/forgot-password/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof GuestAuthForgotPasswordIndexRoute
  '/auth/login': typeof GuestAuthLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof GuestAuthForgotPasswordIndexRoute
  '/auth/login': typeof GuestAuthLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_guest/auth/forgot-password/': typeof GuestAuthForgotPasswordIndexRoute
  '/_guest/auth/login/': typeof GuestAuthLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/forgot-password' | '/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/forgot-password' | '/auth/login'
  id: '__root__' | '/' | '/_guest/auth/forgot-password/' | '/_guest/auth/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuestAuthForgotPasswordIndexRoute: typeof GuestAuthForgotPasswordIndexRoute
  GuestAuthLoginIndexRoute: typeof GuestAuthLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/auth/login/': {
      id: '/_guest/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof GuestAuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/auth/forgot-password/': {
      id: '/_guest/auth/forgot-password/'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof GuestAuthForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuestAuthForgotPasswordIndexRoute: GuestAuthForgotPasswordIndexRoute,
  GuestAuthLoginIndexRoute: GuestAuthLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
