/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRewardsIndexRouteImport } from './routes/_authenticated/rewards/index'
import { Route as AuthenticatedResetPasswordIndexRouteImport } from './routes/_authenticated/reset-password/index'
import { Route as AuthenticatedReferIndexRouteImport } from './routes/_authenticated/refer/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedBusinessesIndexRouteImport } from './routes/_authenticated/businesses/index'
import { Route as AuthenticatedBookIndexRouteImport } from './routes/_authenticated/book/index'
import { Route as GuestAuthLoginIndexRouteImport } from './routes/_guest/auth/login/index'
import { Route as GuestAuthForgotPasswordIndexRouteImport } from './routes/_guest/auth/forgot-password/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRewardsIndexRoute =
  AuthenticatedRewardsIndexRouteImport.update({
    id: '/_authenticated/rewards/',
    path: '/rewards/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedResetPasswordIndexRoute =
  AuthenticatedResetPasswordIndexRouteImport.update({
    id: '/_authenticated/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedReferIndexRoute = AuthenticatedReferIndexRouteImport.update({
  id: '/_authenticated/refer/',
  path: '/refer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/_authenticated/profile/',
    path: '/profile/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBusinessesIndexRoute =
  AuthenticatedBusinessesIndexRouteImport.update({
    id: '/_authenticated/businesses/',
    path: '/businesses/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBookIndexRoute = AuthenticatedBookIndexRouteImport.update({
  id: '/_authenticated/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestAuthLoginIndexRoute = GuestAuthLoginIndexRouteImport.update({
  id: '/_guest/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestAuthForgotPasswordIndexRoute =
  GuestAuthForgotPasswordIndexRouteImport.update({
    id: '/_guest/auth/forgot-password/',
    path: '/auth/forgot-password/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof AuthenticatedBookIndexRoute
  '/businesses': typeof AuthenticatedBusinessesIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/refer': typeof AuthenticatedReferIndexRoute
  '/reset-password': typeof AuthenticatedResetPasswordIndexRoute
  '/rewards': typeof AuthenticatedRewardsIndexRoute
  '/auth/forgot-password': typeof GuestAuthForgotPasswordIndexRoute
  '/auth/login': typeof GuestAuthLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof AuthenticatedBookIndexRoute
  '/businesses': typeof AuthenticatedBusinessesIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/refer': typeof AuthenticatedReferIndexRoute
  '/reset-password': typeof AuthenticatedResetPasswordIndexRoute
  '/rewards': typeof AuthenticatedRewardsIndexRoute
  '/auth/forgot-password': typeof GuestAuthForgotPasswordIndexRoute
  '/auth/login': typeof GuestAuthLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/book/': typeof AuthenticatedBookIndexRoute
  '/_authenticated/businesses/': typeof AuthenticatedBusinessesIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/refer/': typeof AuthenticatedReferIndexRoute
  '/_authenticated/reset-password/': typeof AuthenticatedResetPasswordIndexRoute
  '/_authenticated/rewards/': typeof AuthenticatedRewardsIndexRoute
  '/_guest/auth/forgot-password/': typeof GuestAuthForgotPasswordIndexRoute
  '/_guest/auth/login/': typeof GuestAuthLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/businesses'
    | '/profile'
    | '/refer'
    | '/reset-password'
    | '/rewards'
    | '/auth/forgot-password'
    | '/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/businesses'
    | '/profile'
    | '/refer'
    | '/reset-password'
    | '/rewards'
    | '/auth/forgot-password'
    | '/auth/login'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/book/'
    | '/_authenticated/businesses/'
    | '/_authenticated/profile/'
    | '/_authenticated/refer/'
    | '/_authenticated/reset-password/'
    | '/_authenticated/rewards/'
    | '/_guest/auth/forgot-password/'
    | '/_guest/auth/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedBookIndexRoute: typeof AuthenticatedBookIndexRoute
  AuthenticatedBusinessesIndexRoute: typeof AuthenticatedBusinessesIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedReferIndexRoute: typeof AuthenticatedReferIndexRoute
  AuthenticatedResetPasswordIndexRoute: typeof AuthenticatedResetPasswordIndexRoute
  AuthenticatedRewardsIndexRoute: typeof AuthenticatedRewardsIndexRoute
  GuestAuthForgotPasswordIndexRoute: typeof GuestAuthForgotPasswordIndexRoute
  GuestAuthLoginIndexRoute: typeof GuestAuthLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rewards/': {
      id: '/_authenticated/rewards/'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reset-password/': {
      id: '/_authenticated/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthenticatedResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/refer/': {
      id: '/_authenticated/refer/'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof AuthenticatedReferIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/businesses/': {
      id: '/_authenticated/businesses/'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof AuthenticatedBusinessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/book/': {
      id: '/_authenticated/book/'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof AuthenticatedBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/auth/login/': {
      id: '/_guest/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof GuestAuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/auth/forgot-password/': {
      id: '/_guest/auth/forgot-password/'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof GuestAuthForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedBookIndexRoute: AuthenticatedBookIndexRoute,
  AuthenticatedBusinessesIndexRoute: AuthenticatedBusinessesIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedReferIndexRoute: AuthenticatedReferIndexRoute,
  AuthenticatedResetPasswordIndexRoute: AuthenticatedResetPasswordIndexRoute,
  AuthenticatedRewardsIndexRoute: AuthenticatedRewardsIndexRoute,
  GuestAuthForgotPasswordIndexRoute: GuestAuthForgotPasswordIndexRoute,
  GuestAuthLoginIndexRoute: GuestAuthLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
